apiVersion: v1
kind: Pod
metadata:
  name: fourthpod
  labels:
    tier: backend
spec:
  containers:
  - name: nginxcont
    image: nginx:latest
    ports:
    - containerPort: 80
  nodeSelector:
    hddType: ssd
